<?php
global $conf, $appconf, $tdata;

// Login control - If not, goes to login page especified in config file
// Tools::loginControl();
$auth = new Auth();
$auth->checkLoginAndRedirect('/manager/cursos', '/manager/login');

// Rights control - If not have rigths, goes to home page especified in config file
Tools::rightsControl(['manage', 'view:' . AutoIncludes::getFileName(true)]);

// Xcrud
Tools::loadInclude('xcrud', 'xcrud');

// Init user object
$user = new User($_SESSION['userlogedin']);
$tdata['userlogedin'] = json_encode(['id' => $user->id, 'tipo_inscrito' => $user->tipo_usuario]);

// User is admin
$is_admin = App::getUserTipe($_SESSION['userlogedin']) == $appconf['tipo_admin'] ? true : false;

// Generic xcrud setup
$grid_where   = '';
$row_buttons  = [];

$grid   = [
          'language'          =>  'es',
          'table'             =>  'cursos',
          'table_name'        =>  'Cursos',
          'unset_add'         =>  false,
          'unset_view'        =>  true,
          'unset_remove'      =>  false,
          'unset_csv'         =>  false,
          'unset_print'       =>  false,
          // 'unset_edit'        =>  false,
          'hide_buttons'      =>  ['edit', 'save_edit', 'save_new', 'return'],
          // 'templates'         =>  ['mode(list,view,edit,create)' => 'file.php'],
          // 'vars'              =>  ['var'  =>  [value]],
          // 'hide_button'       =>  'view',  //view, edit, remove, duplicate, add, csv, print, save_new, save_edit, save_return, return
          'list_limit'        =>  25,
          'where'             =>  $grid_where,
          // 'pass_default'      =>  [],
          'search_columns'    =>  ['id_tipo_curso, nombre'],
          'before_insert'     =>  ['App::cursosBeforeInsert', $conf['appinfo']['approot'] . '/include/app.php'],
          'before_update'     =>  ['App::cursosBeforeUpdate',  $_SERVER['DOCUMENT_ROOT'] . '/include/app.php'],
          // 'after_insert'      =>  ['App::sendMailAfterInsert',  $_SERVER['DOCUMENT_ROOT'] . '/include/app.php'],
          // 'row_buttons'       =>  $row_buttons,
          'order_by'          =>  ['nombre', 'asc'],
          'join'              =>  ['id_curso', 'cursos_extend', 'id_curso'],
          'row_actions'       =>  [['activar', 'App::toggleCurso', $conf['appinfo']['approot'] . '/include/app.php'],
                                   ['desactivar', 'App::toggleCurso', $conf['appinfo']['approot'] . '/include/app.php']],
          'row_buttons'       =>  [['#',
                                    'Activar',
                                    'fas fa-toggle-off',
                                    'xcrud-action',
                                    array(  // set action vars to the button
                                        'data-task'     => 'action',
                                        'data-action'   => 'activar',
                                        'data-primary'  => '{id_curso}')
                                    ,
                                    array(  // set condition ( when button must be shown)
                                        'activo',
                                        '!=',
                                        '1')
                                    ],
                                    ['#',
                                     'Desactivar',
                                     'fas fa-toggle-on',
                                     'xcrud-action',
                                     array(  // set action vars to the button
                                        'data-task'     => 'action',
                                        'data-action'   => 'desactivar',
                                        'data-primary'  => '{id_curso}')
                                     ,
                                     array(  // set condition ( when button must be shown)
                                        'activo',
                                        '=',
                                        '1')
                                    ]
                                ]

];

// join( field, joined_table, join_on_field [, alias] [, not_insert] )

// Fields xcrud setup
$fields = [
  'id_curso'            =>  [ 'label'            =>  '',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  false,
                              'disabled'         =>  false,
                              'tab'              =>  'Ficha del curso'
                            ],
  'id_tipo_curso'       =>  [ 'label'            =>  'Tipo curso',
                              'column_name'      =>  'Tipo curso',
                              'column_callback'  =>  false,
                              'columns'          =>  true,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Ficha del curso',
                              'relation'         =>  ['tipos_curso', 'id_tipo_curso', 'nombre'],
                              // 'readonly'         => ['edit', 'view', 'create'],
                              'pass_default'     => 1,
                              'validation_required' => 1,
                              'set_attr'         =>  ['details_row' => 'form-group col-md-12', 'details_field_cell' => 'col-sm-6']
                            ],
  'pendiente_acreditacion' =>  [ 'label'            =>  'Pendiente de adreditación',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  true,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Ficha del curso',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-6', 'details_field_cell' => 'col-sm-12']
                            ],
  'activo'              =>  [ 'label'            =>  'Activo',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  true,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Ficha del curso',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-6', 'details_field_cell' => 'col-sm-12']
                            ],
  'nombre'              =>  [ 'label'            =>  'Nombre',
                              'column_name'      =>  'Curso',
                              'column_callback'  =>  false,
                              'columns'          =>  true,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'validation_required' => 3,
                              'column_pattern'   =>  '<a href="#" class="xcrud-action" data-task="edit" data-primary="{id_curso}">{value}</a>',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-6', 'details_field_cell' => 'col-sm-12'],
                              'tab'              =>  'Ficha del curso'
                            ],
  'id_categoria'        =>  [ 'label'            =>  'Categoria',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  true,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Ficha del curso',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-6', 'details_field_cell' => 'col-sm-12'],
                              'relation'         =>   ['categorias', 'id_categoria', 'nombre']
                            ],
  'url_curso_externo'   =>  [ 'label'            =>  'Url si curso externo',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  true,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'set_attr'         =>  ['details_row' => 'form-group col-md-6', 'details_field_cell' => 'col-sm-12'],
                              // 'validation_required' => 1,
                              // 'set_attr'         =>  ['maxlength' => 25],
                              'tab'              =>  'Ficha del curso'
                            ],
  'id_moodle'           =>  [ 'label'            =>  'Identificador de Moodle',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  true,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'validation_required' => 1,
                              'set_attr'         =>  ['maxlength' => 25],
                              'tab'              =>  'Ficha del curso'
                            ],
  'moodle_pass'         =>  [ 'label'            =>  'Contraseña de Moodle',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'field_type'       =>  'text',
                              'validation_required' => 3,
                              'field_callback'   =>  ['App::aesDecrypt', $conf['appinfo']['approot'] . '/include/app.php' ],
                              'set_attr'         =>  ['maxlength' => 25, 'data-required' => 3],
                              'tab'              =>  'Ficha del curso'
                            ],
  'precio'              =>  [ 'label'            =>  'Precio del curso',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Ficha del curso'
                            ],
  'director'            =>  [ 'label'            =>  'Director del curso',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Ficha del curso',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-12', 'details_field_cell' => 'col-sm-12']
                            ],
  'dirigido_a'          =>  [ 'label'            =>  'Dirigido a',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Ficha del curso',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-12', 'details_field_cell' => 'col-sm-12']
                            ],
  'patrocinado_por'     =>  [ 'label'            =>  'Patrocinado por',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Ficha del curso',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-12', 'details_field_cell' => 'col-sm-12']
                            ],
  'destacado'           =>  [ 'label'            =>  'Curso destacado',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Gestión del curso',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-6', 'details_field_cell' => 'col-sm-6'],
                            ],
  'url_id'              =>  [ 'label'            =>  'Identificador de URL',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'validation_required' => 1,
                              'tab'              =>  'Gestión del curso',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-6', 'details_field_cell' => 'col-sm-12'],
                            ],
  'id_entidad_acreditadora' =>  [ 'label'            =>  'Entidad/es acreditadora/s',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Gestión del curso',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-12', 'details_field_cell' => 'col-sm-7'],
                              'relation'         =>  ['entidades_acreditadoras', 'id_entidad', 'nombre', '', '', true]
                            ],
  'fecha_solicitud_acreditacion'  =>  [ 'label'  =>  'Fecha solicitud acreditación',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'set_attr'         =>  ['details_row' => 'form-group col-md-6', 'details_field_cell' => 'col-sm-12'],
                              'tab'              =>  'Gestión del curso',
                            ],
  'fecha_recepcion_acreditacion'  =>  [ 'label'  =>  'Fecha recepción acreditación',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'set_attr'         =>  ['details_row' => 'form-group col-md-6', 'details_field_cell' => 'col-sm-12'],
                              'tab'              =>  'Gestión del curso',
                            ],
  'fecha_inicio'        =>  [ 'label'            =>  'Fecha de incio del curso',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'set_attr'         =>  ['details_row' => 'form-group col-md-6', 'details_field_cell' => 'col-sm-12'],
                              'tab'              =>  'Gestión del curso',
                            ],
  'fecha_fin'           =>  [ 'label'            =>  'Fecha fin del curso',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'set_attr'         =>  ['details_row' => 'form-group col-md-6', 'details_field_cell' => 'col-sm-12'],
                              'tab'              =>  'Gestión del curso',
                            ],
  'creditos'            =>  [ 'label'            =>  'Creditos',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'field_callback'   =>  ['App::arrangeCoursefields', $conf['appinfo']['approot'] . '/include/app.php' ],
                              'set_attr'         =>  ['details_row' => 'form-group col-md-6', 'details_field_cell' => 'col-sm-4'],
                              'tab'              =>  'Gestión del curso',
                            ],
  'horas_lectivas'      =>  [ 'label'            =>  'Horas lectivas',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'set_attr'         =>  ['details_row' => 'form-group col-md-6', 'details_field_cell' => 'col-sm-4'],
                              'tab'              =>  'Gestión del curso',
                            ],
  'numero_registro'     =>  [ 'label'            =>  'Número de registro',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'set_attr'         =>  ['details_row' => 'form-group col-md-12', 'details_field_cell' => 'col-sm-4'],
                              'tab'              =>  'Gestión del curso',
                            ],
  'plantilla_certificado'=>  [ 'label'            =>  'Plantilla certificado - Pag. 1',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'field_type'       =>  ['file', '', ['path' => $conf['appinfo']['approot'] . 'public/uploads/certificados/backgrounds/']],
                              'set_attr'         =>  ['details_row' => 'form-group col-md-12', 'details_field_cell' => 'col-sm-12'],
                              'tab'              =>  'Gestión del curso',
                            ],
  'plantilla_certificado_2'=>  [ 'label'            =>  'Plantilla certificado - Pag. 2',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'field_type'       =>  ['file', '', ['path' => $conf['appinfo']['approot'] . 'public/uploads/certificados/backgrounds/']],
                              'set_attr'         =>  ['details_row' => 'form-group col-md-12', 'details_field_cell' => 'col-sm-12'],
                              'tab'              =>  'Gestión del curso',
                            ],
  'imagen'              =>  [ 'label'            =>  'Imagen curso',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'field_type'       =>  ['image', '', ['path' => $conf['appinfo']['approot'] . 'public/img/']],
                              'set_attr'         =>  ['details_row' => 'form-group col-md-12', 'details_field_cell' => 'col-sm-12'],
                              'tab'              =>  'Gestión del curso',
                            ],
  'cursos_extend.descripcion' =>  [ 'label'            =>  'Descripción del curso',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Descripción del curso',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-12', 'details_field_cell' => 'col-sm-12'],
                            ],
  'cursos_extend.objetivos' =>  [ 'label'        =>  'Objetivos del curso',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Descripción del curso',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-12', 'details_field_cell' => 'col-sm-12'],
                            ],
  'cursos_extend.programa' =>  [ 'label'            =>  'Programa del curso',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Descripción del curso',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-12', 'details_field_cell' => 'col-sm-12'],
                            ],
  'cursos_extend.docentes' =>  [ 'label'            =>  'Docentes del curso',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Descripción del curso',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-12', 'details_field_cell' => 'col-sm-12'],
                            ],
  'cursos_extend.evaluacion' =>  [ 'label'            =>  'Evaluación del curso',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Descripción del curso',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-12', 'details_field_cell' => 'col-sm-12'],
                            ],
  'cursos_extend.creditos_text' =>  [ 'label'            =>  'Texto créditos del curso',
                              'column_name'      =>  '',
                              'column_callback'  =>  false,
                              'columns'          =>  false,
                              'fields'           =>  true,
                              'disabled'         =>  false,
                              'tab'              =>  'Descripción del curso',
                              'set_attr'         =>  ['details_row' => 'form-group col-md-12', 'details_field_cell' => 'col-sm-12'],
                            ],
];

$nesteds_id_curso = [
                          ['nested_name'  => 'Textos legales',
                           'nested_table' => 'curso_texto_legal',
                           'nested_field' => 'id_curso',
                           'grid'         => [ 'table_name' => ' ',
                                               // 'unset_add'         =>  false,
                                               'unset_view'        =>  true,
                                               // 'unset_remove'      =>  false,
                                               // 'unset_csv'         =>  false,
                                               // 'unset_print'       =>  false,
                                               // 'unset_edit'        =>  false,
                                               'hide_buttons'      =>  ['edit', 'save_edit', 'save_new'],
                                               'vars'              =>  ['hide_edit_buttons_text' => true],
                                               'hide_'

                           ],
                          'fields'  => [
                            'id_curso'      =>  ['label'            =>  'Curso',
                                                  'column_name'     =>  '',
                                                  'column_callback' =>  false,
                                                  'columns'         =>  false,
                                                  'fields'          =>  false,
                                                  'disabled'        =>  false,
                                                  // 'tab'             =>  'Cursos del usuario'
                                                ],
                            'id_texto_legal'=>  ['label'            =>  'Texto legal',
                                                'column_name'       =>  'Texto legal',
                                                'column_callback'   =>  false,
                                                'columns'           =>  true,
                                                'fields'            =>  true,
                                                // 'disabled'          =>  [true, 'edit'],
                                                'tab'               =>  false,
                                                'relation'          =>  ['textos_legales', 'id_texto_legal', 'titulo', 'id_tipo_texto_legal = 2'],
                                                // 'column_pattern'    =>  '<a href="#" class="xcrud-action" data-task="edit" data-primary="{id_usuario_curso}">{value}</a>',
                                                'column_pattern'    =>  '<a href="/manager/textoslegales?fid={id_texto_legal}&faction=editrow" class="" target="_blank">{value}</a>'
                                                ]
                          ]
                        ]
                    ];
$fields['id_curso']['nested'] = $nesteds_id_curso;

$tdata['content'] = Tools::xcrud($grid, $fields)->render((isset($_GET['action']) ? $_GET['action'] : false), (isset($_GET['id']) ? $_GET['id'] : false));
?>
